### ISSUE TITLE
Refactor : MainPage

### ISSUE THREAD

**Issue by blingblin-g** [42-world/42world-Frontend#49]
## TODO
- [x] main page 컴포넌트 수정
- [x] 더이상 쪼갤 수 없을 때까지 쪼갠다
- [x] 반응형 페이지로 만든다.
- [x] 기존에 돌아가던 기능과 디자인 모두 만족하도록 만든다.
